// <auto-generated />
using System;
using GoldenFreshCart.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoldenFreshCart.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GoldenFreshCart.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "🥦",
                            Name = "Fruits & Vegetables",
                            Slug = "fruits-vegetables"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "🥛",
                            Name = "Dairy & Eggs",
                            Slug = "dairy-eggs"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "🍞",
                            Name = "Bakery",
                            Slug = "bakery"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "🥩",
                            Name = "Meat & Seafood",
                            Slug = "meat-seafood"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "🧃",
                            Name = "Beverages",
                            Slug = "beverages"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "🍿",
                            Name = "Snacks",
                            Slug = "snacks"
                        });
                });

            modelBuilder.Entity("GoldenFreshCart.API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GoldenFreshCart.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("GoldenFreshCart.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 7, 32, 54, 124, DateTimeKind.Utc).AddTicks(7393),
                            Description = "Fresh organic bananas, perfect for smoothies and snacking.",
                            ImageUrl = "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400",
                            IsAvailable = true,
                            Name = "Organic Bananas",
                            Price = 25.00m,
                            Stock = 100,
                            Unit = "bunch"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 7, 32, 54, 125, DateTimeKind.Utc).AddTicks(947),
                            Description = "Crisp and sweet red apples sourced from local orchards.",
                            ImageUrl = "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400",
                            IsAvailable = true,
                            Name = "Red Apples",
                            Price = 35.00m,
                            Stock = 80,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 7, 32, 54, 125, DateTimeKind.Utc).AddTicks(951),
                            Description = "Tender baby spinach leaves, washed and ready to eat.",
                            ImageUrl = "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400",
                            IsAvailable = true,
                            Name = "Baby Spinach",
                            Price = 39.00m,
                            Stock = 60,
                            Unit = "bag"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 7, 32, 54, 125, DateTimeKind.Utc).AddTicks(952),
                            Description = "Vine-ripened cherry tomatoes bursting with flavour.",
                            ImageUrl = "https://images.unsplash.com/photo-1561136594-7f68413baa99?w=400",
                            IsAvailable = true,
                            Name = "Cherry Tomatoes",
                            Price = 32.00m,
                            Stock = 70,
                            Unit = "punnet"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 4, 1, 7, 32, 54, 125, DateTimeKind.Utc).AddTicks(968),
                            Description = "Full-cream fresh whole milk from grass-fed cows.",
                            ImageUrl = "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400",
                            IsAvailable = true,
                            Name = "Whole Milk",
                            Price = 22.00m,
                            Stock = 120,
                            Unit = "litre"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 4, 1, 7, 32, 54, 125, DateTimeKind.Utc).AddTicks(970),
                            Description = "A dozen large free-range eggs.",
                            ImageUrl = "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400",
                            IsAvailable = true,
                            Name = "Free Range Eggs",
                            Price = 59.00m,
                            Stock = 90,
                            Unit = "dozen"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 4, 1, 7, 32, 54, 125, DateTimeKind.Utc).AddTicks(972),
                            Description = "Thick and creamy authentic Greek-style yoghurt.",
                            ImageUrl = "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400",
                            IsAvailable = true,
                            Name = "Greek Yoghurt",
                            Price = 45.00m,
                            Stock = 55,
                            Unit = "500g"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 4, 1, 7, 32, 54, 125, DateTimeKind.Utc).AddTicks(973),
                            Description = "Artisan sourdough baked fresh daily with a tangy crust.",
                            ImageUrl = "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400",
                            IsAvailable = true,
                            Name = "Sourdough Loaf",
                            Price = 69.00m,
                            Stock = 40,
                            Unit = "loaf"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 4, 1, 7, 32, 54, 125, DateTimeKind.Utc).AddTicks(975),
                            Description = "Buttery, flaky French croissants baked fresh each morning.",
                            ImageUrl = "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400",
                            IsAvailable = true,
                            Name = "Croissants",
                            Price = 49.00m,
                            Stock = 35,
                            Unit = "4 pack"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 1, 7, 32, 54, 125, DateTimeKind.Utc).AddTicks(976),
                            Description = "Skinless free-range chicken breast fillets.",
                            ImageUrl = "https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=400",
                            IsAvailable = true,
                            Name = "Chicken Breast",
                            Price = 119.00m,
                            Stock = 65,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 1, 7, 32, 54, 125, DateTimeKind.Utc).AddTicks(978),
                            Description = "Fresh Atlantic salmon fillets, skin on.",
                            ImageUrl = "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=400",
                            IsAvailable = true,
                            Name = "Atlantic Salmon",
                            Price = 159.00m,
                            Stock = 30,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 4, 1, 7, 32, 54, 125, DateTimeKind.Utc).AddTicks(979),
                            Description = "Freshly squeezed 100% pure orange juice, no added sugar.",
                            ImageUrl = "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400",
                            IsAvailable = true,
                            Name = "Orange Juice",
                            Price = 49.00m,
                            Stock = 75,
                            Unit = "litre"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 4, 1, 7, 32, 54, 125, DateTimeKind.Utc).AddTicks(981),
                            Description = "Natural sparkling mineral water, lightly carbonated.",
                            ImageUrl = "https://images.unsplash.com/photo-1564419320461-6870880221ad?w=400",
                            IsAvailable = true,
                            Name = "Sparkling Water",
                            Price = 25.00m,
                            Stock = 110,
                            Unit = "1.5L"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 4, 1, 7, 32, 54, 125, DateTimeKind.Utc).AddTicks(982),
                            Description = "Classic beef hot dog sausages, ready to grill or boil.",
                            ImageUrl = "https://images.unsplash.com/photo-1599599810694-b5b37304c041?w=400",
                            IsAvailable = true,
                            Name = "Hot Dog",
                            Price = 89.00m,
                            Stock = 85,
                            Unit = "6 pack"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 4, 1, 7, 32, 54, 125, DateTimeKind.Utc).AddTicks(984),
                            Description = "70% cocoa rich dark chocolate bar.",
                            ImageUrl = "https://images.unsplash.com/photo-1548907040-4baa42d10919?w=400",
                            IsAvailable = true,
                            Name = "Dark Chocolate",
                            Price = 39.00m,
                            Stock = 95,
                            Unit = "bar"
                        });
                });

            modelBuilder.Entity("GoldenFreshCart.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@goldenfreshcart.com",
                            Name = "Bithun",
                            PasswordHash = "$2a$11$7zHPLdUbavJebJ48NqJIx.AE4eBA3SpOFuv4r5m6.L.3DYcf.jE4K",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("GoldenFreshCart.API.Models.Order", b =>
                {
                    b.HasOne("GoldenFreshCart.API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoldenFreshCart.API.Models.OrderItem", b =>
                {
                    b.HasOne("GoldenFreshCart.API.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoldenFreshCart.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GoldenFreshCart.API.Models.Product", b =>
                {
                    b.HasOne("GoldenFreshCart.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GoldenFreshCart.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("GoldenFreshCart.API.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GoldenFreshCart.API.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
